name: KarhuAlerts
version: '${project.version}'
main: ir.alijk.karhualerts.KarhuAlerts
authors: [ Alijk ]
description: Karhu Anticheat proxy wide alert system
depend:
  - KarhuAPI
  - PlaceholderAPI
api-version: 1.13